version: '3.5'
services:
  app-web:
    build: 
      context: react_native/
      dockerfile: Dockerfile.web
    volumes:
      - ./react_native/sababi-front:/usr/share
    ports:
      - "19006:19006"
    environment:
      - STAGE=DEV
      - WATCHPACK_POLLING=true

  app-android:
    build: 
      context: react_native/
      dockerfile: Dockerfile.android
    volumes:
      - ./react_native/sababi-front:/usr/share
    ports:
      - "19007:19007"
    environment:
      - STAGE=DEV
      - WATCHPACK_POLLING=true

  # app-ios:
  #   build: 
  #     context: react_native/
  #     dockerfile: Dockerfile.ios
  #   volumes:
  #     - ./react_native/sababi-front:/usr/share
  #   ports:
  #     - "19008:19008"
  #   environment:
  #     - STAGE=DEV
  #     - WATCHPACK_POLLING=true

  flask-server:
    build: server/.
    volumes:
      - ./server/:/usr/server
    ports:
      - "8081:8081"
    environment:
      - STAGE=DEV
